### ISSUE TITLE
[FEATURE] Create Account module

### ISSUE THREAD

**Issue by idylicaro** [idylicaro/go-bank#2]
## Description
The account domain layer.

## Tasks
- [x] Create Entities.
- [x] Create ObjectValue.
- [x] Create Costumer Aggregate.
- [x] Create Repository Interface.
- [x] Create Memory Repository.
- [x] Create Transaction service
- [x] Create the deposit function.
- [x] Create the withdraw function.
- [x] Make tests.
