### ISSUE TITLE
[FEATURE] Create transaction worker for deposit and withdraw

### ISSUE THREAD

**Issue by idylicaro** [idylicaro/go-bank#8]
## Description
The account deposit and withdraw queue pipeline.

## Tasks

- [ ] Create RabbitMQ Adapter.
- [ ] Create worker structure.
- [ ] Create Producer
- [ ] Create Consumer
- [ ] Create flow diagram.
- [ ] Make tests.

## Dependencies:

- #2

**Comment by idylicaro** [comment]
This architecture path is correct? The best way is to use simple transaction?
